---
- name: setting ycsb_workload var
  set_fact:
    ycsb_workload: "workloada"

- name: Generate workloads
  k8s:
    definition: "{{ lookup('template', 'configmap.yml.j2') | from_yaml }}"

- name: Load Data Into Database
  k8s:
    definition: "{{ lookup('template', 'workload.yml.j2') }}"

- name: Wait for Load Job to Succeed...
  k8s_facts:
    kind: Job
    api_version: batch/v1
    name: 'ycsb-data-load-job-{{ ycsb_workload }}-{{ trunc_uuid }}'
    namespace: "{{ operator_namespace }}"
    label_selectors:
      - name = 'ycsb-load-{{ trunc_uuid }}'
  register: ycsb_load_pod
  until: "ycsb_load_pod | json_query('resources[].status.succeeded')"
  retries: 1000
  delay: 20
