---
  - name: Start Server(s)
    k8s:
      definition: "{{ lookup('template', 'server.yml.j2') | from_yaml }}"
    register: servers
    with_sequence: start=0 count={{uperf.pair}}

  - name: Wait for pods to be running....
    k8s_facts:
      kind: Pod
      api_version: v1
      namespace: '{{ operator_namespace }}'
      label_selectors:
        - app = uperf-bench-server
    register: server_pods
    until: "'Running' in (server_pods | json_query('resources[].status.phase'))"
    retries: 10
    delay: 10

  - name: Capture operator information
    k8s_facts:
      kind: Pod
      api_version: v1
      namespace: '{{ operator_namespace }}'
      label_selectors:
        - name = benchmark-operator
    register: bo

  - name: Generate uperf test
    k8s:
      definition: "{{ lookup('template', 'configmap.yml.j2') | from_yaml }}"

  - name: Start Client(s)
    k8s:
      definition: "{{ lookup('template', 'workload.yml.j2') | from_yaml }}"
    with_items: "{{ server_pods.resources }}"
    when: server_pods.resources|length > 0 and (store_results is not defined or (store_results is defined and not store_results))

  - name: Start Client(s) - store results
    k8s:
      definition: "{{ lookup('template', 'workload_store.yml.j2') | from_yaml }}"
    with_items: "{{ server_pods.resources }}"
    when: server_pods.resources|length > 0 and store_results is defined and store_results

  - name: Check if all clients are up
    k8s_facts:
      kind: Pod
      api_version: v1
      namespace: '{{ operator_namespace }}'
      label_selectors:
        - app = uperf-bench-client
    register: client_pods
    until: "uperf.pair  == (client_pods | json_query('resources[].status.podIP')|length)"
    retries: 50
    delay: 10

  - name: Signal workload
    command: "redis-cli set start true"

  - name: Waiting for pods to complete....
    k8s_facts:
      kind: pod
      api_version: v1
      namespace: '{{ operator_namespace }}'
      label_selectors:
        - app = uperf-bench-client
    register: client_pods
    until: "'Succeeded' in (client_pods | json_query('resources[].status.phase'))"
    retries: 30
    delay: 10
