---
- name: setting ycsb_workload var
  set_fact:
    ycsb_workload: "{{ item }}"

- name: Generate workloads
  k8s:
    definition: "{{ lookup('template', 'configmap.yml.j2') | from_yaml }}"

- name: Run YCSB Workload
  k8s:
    definition: "{{ lookup('template', 'workload.yml.j2') }}"

- name: Wait for YCSB Workload Job to Succeed...
  k8s_facts:
    kind: Job
    api_version: batch/v1
    name: 'ycsb-bench-job-{{ ycsb_workload }}-{{ trunc_uuid }}'
    namespace: "{{ operator_namespace }}"
    label_selectors:
      - name = 'ycsb-run-{{ trunc_uuid }}'
  register: ycsb_bench
  until: "ycsb_bench | json_query('resources[].status.succeeded')"
  retries: 1000
  delay: 20
